###
POST /api/facts/insert HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "fact": "BestTVCharacters",
  "values": ["Logan", "Kendall", "Shiv"]
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

###
POST /api/facts/insert HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "fact": "BestTVCharacters",
  "values": ["Logan", "Tom", "Greg"]
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST /api/facts/insert HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "fact": "BestTVCharacters",
  "values": ["Monk"]
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST /api/facts/insert HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "fact": "BestTVCharacters",
  "values": ["Dolores", "Host", "Host"]
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
